
PYTHON=python3

all: lit01 lit02 lit03 lit04-1 lit04-2 lit05 lit06a lit06b lit07 lit08 lit09

lit01: 
	$(PYTHON) simo-lit_01-Laude-AIPAdv_2013-silica.py
lit02: 
	$(PYTHON) simo-lit_02-Laude-AIPAdv_2013-silicon.py
lit03: 
	$(PYTHON) simo-lit_03-Beugnot-NatComm_2014.py
lit04-1: 
	$(PYTHON) simo-lit_04-no_pillar-Van_Laer-NP_2015.py
lit04-2: 
	$(PYTHON) simo-lit_04-pillar-Van_Laer-NP_2015.py
lit05: 
	$(PYTHON) simo-lit_05-Van_Laer-NJP_2015.py
lit06a: 
	$(PYTHON) simo-lit_06_1-Florez-NatComm_2016-d550nm.py
lit06b: 
	$(PYTHON) simo-lit_06_2-Florez-NatComm_2016-d1160nm.py
lit07: 
	$(PYTHON) simo-lit_07-Kittlaus-NatPhot_2016.py
lit08: 
	$(PYTHON) simo-lit_08-Kittlaus-NatComm_2017.py
lit09: 
	$(PYTHON) simo-lit_09-Morrison-Optica_2017.py
