
PYTHON=python3

all: tut01 tut02 tut03a tut03b tut04 tut05 tut06 tut06 tut07 tut08 tut09 tut10

tut01: 
	$(PYTHON) simo-tut_01-first_calc.py 
tut02: 
	$(PYTHON) simo-tut_02-gain_spectra-npsave.py 
tut03a: 
	$(PYTHON) simo-tut_03_1-dispersion-npload.py 
tut03b: 
	$(PYTHON) simo-tut_03_2-dispersion-multicore.py 
tut04: 
	$(PYTHON) simo-tut_04-scan_widths.py 
tut05: 
	$(PYTHON) simo-tut_05-convergence_study.py 
tut06: 
	$(PYTHON) simo-tut_06-silica_nanowire.py 
tut07: 
	$(PYTHON) simo-tut_07-slot.py 
tut08: 
	$(PYTHON) simo-tut_08-slot_coated-scan.py 
tut09: 
	$(PYTHON) simo-tut_09-anisotropy.py
tut10: 
	$(PYTHON) simo-tut_10-onion.py
